# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UITemplates/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(442, 500)
        Login.setMinimumSize(QtCore.QSize(400, 500))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.email_line = QtWidgets.QLineEdit(Login)
        self.email_line.setStyleSheet("min-height:30px;")
        self.email_line.setText("")
        self.email_line.setObjectName("email_line")
        self.verticalLayout.addWidget(self.email_line)
        self.password_line = QtWidgets.QLineEdit(Login)
        self.password_line.setStyleSheet("min-height:30px;")
        self.password_line.setObjectName("password_line")
        self.verticalLayout.addWidget(self.password_line)
        self.login_button = QtWidgets.QPushButton(Login)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", " "))
        self.email_line.setPlaceholderText(_translate("Login", "Номер телефону"))
        self.password_line.setPlaceholderText(_translate("Login", "Пароль"))
        self.login_button.setText(_translate("Login", "Вхід"))


