# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UITemplates/master.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Master(object):
    def setupUi(self, Master):
        Master.setObjectName("Master")
        Master.resize(1000, 600)
        Master.setMinimumSize(QtCore.QSize(1000, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Master)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.orders_table = QtWidgets.QTableView(Master)
        self.orders_table.setObjectName("orders_table")
        self.verticalLayout.addWidget(self.orders_table)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Master)
        QtCore.QMetaObject.connectSlotsByName(Master)

    def retranslateUi(self, Master):
        _translate = QtCore.QCoreApplication.translate
        Master.setWindowTitle(_translate("Master", " "))


