# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UITemplates/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(400, 500)
        Register.setMinimumSize(QtCore.QSize(400, 500))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Register)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.email_line = QtWidgets.QLineEdit(Register)
        self.email_line.setStyleSheet("min-height:30px;")
        self.email_line.setObjectName("email_line")
        self.verticalLayout.addWidget(self.email_line)
        self.name_line = QtWidgets.QLineEdit(Register)
        self.name_line.setStyleSheet("min-height:30px;")
        self.name_line.setObjectName("name_line")
        self.verticalLayout.addWidget(self.name_line)
        self.password_line = QtWidgets.QLineEdit(Register)
        self.password_line.setStyleSheet("min-height:30px;")
        self.password_line.setObjectName("password_line")
        self.verticalLayout.addWidget(self.password_line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_redirect_button = QtWidgets.QPushButton(Register)
        self.login_redirect_button.setObjectName("login_redirect_button")
        self.horizontalLayout.addWidget(self.login_redirect_button)
        self.register_button = QtWidgets.QPushButton(Register)
        self.register_button.setObjectName("register_button")
        self.horizontalLayout.addWidget(self.register_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", " "))
        self.email_line.setPlaceholderText(_translate("Register", "Номер телефону"))
        self.name_line.setPlaceholderText(_translate("Register", "Ім'я"))
        self.password_line.setPlaceholderText(_translate("Register", "Пароль"))
        self.login_redirect_button.setText(_translate("Register", "Вхід"))
        self.register_button.setText(_translate("Register", "Реєстрація"))


